--- Benchmark Report Generator
--- Generates per-benchmark reports and merged summary
--- Usage: nvim --headless -c "lua dofile('bench/scripts/report_generator.lua')" -c "qa!"

local rm = dofile(vim.fn.getcwd() .. "/bench/scripts/result_manager.lua")

local M = {}

function M.generate_all()
  local ts = rm.resolve_timestamp()
  local run_dir = rm.base_run_dir()

  io.write(string.format("=== Report Generation ===\n"))
  io.write(string.format("Run: %s\n", ts))
  io.write(string.format("Dir: %s\n", run_dir))

  if vim.fn.isdirectory(run_dir) ~= 1 then
    io.write(string.format("Run directory not found: %s\n", run_dir))
    io.write("Falling back to latest historical run...\n")
    local dirs = vim.fn.globpath(rm.historical_dir, "*", false, true)
    table.sort(dirs)
    if #dirs > 0 then
      ts = vim.fn.fnamemodify(dirs[#dirs], ":t")
      run_dir = rm.historical_dir .. "/" .. ts
      io.write(string.format("Using latest: %s\n", ts))
    else
      io.write("No historical runs found.\n")
      return {}
    end
  end

  -- Merge all sub-benchmark results into results.json + summary.md
  io.write("\n--- Merging results ---\n")
  local merged = rm.merge_run_results(ts)

  -- Load historical runs for trend reports
  io.write("\n--- Loading historical data ---\n")
  local historical = rm.load_historical_runs(50)

  -- Generate individual benchmark reports (already done by each benchmark's ctx:generate_report())
  io.write("\n--- Individual reports already generated by each benchmark ---\n")

  -- Generate per-category supplemental reports using historical data
  local results_dir = {}
  if merged and merged.results then
    local result_path = run_dir .. "/results.json"
    results_dir = { title = "Merged Results", path = result_path }
  end

  io.write(string.format("\n=== Reports Ready ===\n"))
  io.write(string.format("Merged results: %s/results.json\n", run_dir))
  io.write(string.format("Summary report: %s/summary.md\n", run_dir))
  io.write(string.format("Per-benchmark reports in each subdirectory\n"))

  return {
    { title = "Merged Results", path = run_dir .. "/results.json" },
    { title = "Summary", path = run_dir .. "/summary.md" },
  }
end

return M
