-- User configuration overrides
-- Place your personal settings here. This file is loaded after everything else.
--
-- Examples:
--   vim.opt.tabstop = 2
--   vim.opt.shiftwidth = 2
--   require("managers.theme").apply("tokyonight-night")
--   vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Diagnostics" })
--
-- No return value needed — this file is loaded directly via require(), not as a plugin spec.
