vim.keymap.set("n", "<leader>w", "<cmd>update<CR>", { desc = "Save file" })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Close window" })

vim.keymap.set("n", "<leader>ff", function()
    require("managers.picker").find_files()
end, { desc = "Find files" })
vim.keymap.set("n", "<leader>fg", function()
    require("managers.picker").live_grep()
end, { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb", function()
    require("managers.picker").buffers()
end, { desc = "Find buffers" })
vim.keymap.set("n", "<leader>fo", function()
    require("managers.picker").oldfiles()
end, { desc = "Find old files" })
vim.keymap.set("n", "<leader>fh", function()
    require("managers.picker").help_tags()
end, { desc = "Help tags" })
vim.keymap.set("n", "<leader>gf", function()
    require("managers.picker").git_files()
end, { desc = "Git files" })
vim.keymap.set("n", "<leader>gc", function()
    require("managers.picker").git_commits()
end, { desc = "Git commits" })
